name: Android CI Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Gradle Action - Build
        uses: gradle/gradle-build-action@v2.1.0
        env:
          CI: true
        with:
          gradle-version: 6.5
          arguments: build
      - name: Gradle Action - Assemble
        uses: gradle/gradle-build-action@v2.1.0
        env:
          CI: true
        with:
          gradle-version: 6.5
          arguments: assembleRelease
      - name: Find all JS files and fail if found
        uses: DovnarAlexander/github-action-file-detection@master
        with:
          wildcard: '*.apk'
          exit_code_found: 1
          exit_code_not_found: 0
          base_path: .
