name: Android CI Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Gradle Action - Build
        uses: gradle/gradle-build-action@v2.1.0
        env:
          CI: true
        with:
          gradle-version: 6.5
          arguments: build
      - name: Gradle Action - Assemble
        uses: gradle/gradle-build-action@v2.1.0
        env:
          CI: true
        with:
          gradle-version: 6.5
          arguments: assembleRelease
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./build/outputs/apk/release/APK-Extractor-release-unsigned.apk ./artifacts 
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0  
        with:
          name: Android
          path: artifacts
