name: Android CI Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Gradle Action - Build
        uses: gradle/gradle-build-action@v2.1.0
        env:
          CI: true
        with:
          gradle-version: 6.5
          arguments: build
      - name: Gradle Action - Assemble
        uses: gradle/gradle-build-action@v2.1.0
        env:
          CI: true
        with:
          gradle-version: 6.5
          arguments: assembleRelease
      - name: Releasing using Hub
        uses: yurakurets/action-release-debugapk@master
        env:
          REPO_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.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 }}
          APK_FOLDER: android/app/build/outputs/apk/release/app-release.apk
          APP_FOLDER: android/app
          RELEASE_TITLE: New Build
